# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_pulse_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse_data',
            old_name='ticker',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='temp_data',
            old_name='ticker',
            new_name='name',
        ),
    ]
