# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20170818_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse_data',
            old_name='initial',
            new_name='hRate',
        ),
        migrations.RenameField(
            model_name='temp_data',
            old_name='initial',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='pulse_data',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='pulse_data',
            name='times',
        ),
        migrations.RemoveField(
            model_name='temp_data',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='temp_data',
            name='times',
        ),
    ]
